# /etc/elastalert/config.yaml 
es_host: "localhost"
es_port: 9200
 
writeback_index: "elastalert_status"
buffer_time:
  minutes: 5
run_every:
  minutes: 1
alert_time_limit:
  days: 2
rules_folder: /etc/elastalert/rules
